apiVersion: v1
kind: Service
metadata:
  name: frontend-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: frontendservice
  ports:
  - name: frontendservice
    protocol: TCP
    port: 8080
    targetPort: 8080