apiVersion: v1
kind: Service
metadata:
  name: profile-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: profileservice
  ports:
  - name: profileservice
    protocol: TCP
    port: 80
    targetPort: 80