apiVersion: v1
kind: Service
metadata:
  name: user-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
  - name: userservice
    protocol: TCP
    port: 80
    targetPort: 80