name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UserService
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Analyze with SonarCloud
      uses: Secbyte/dotnet-sonarscanner@v2.3
      with:
        buildCommand: dotnet build .
    #     testCommand: dotnet test .
        projectKey: UserService_Hyves-2.0-Backend
        projectName: UserService_Hyves-2.0-Backend
        sonarOrganisation: bramhurkmans
        beginArguments: >
            /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
            UserService.csproj
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
