name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UserService
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarScanner for .NET 6 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@v2.1.2
      with:
        # The key of the SonarQube project
        sonarProjectKey: UserService_Hyves-2.0-Backend
        # The name of the SonarQube project
        sonarProjectName: UserService_Hyves-2.0-Backend
        # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
        sonarOrganization: bramhurkmans
        dotnetDisableTests: true
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
