name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UserService
    steps:
    - name: Sonarscanner for dotnet
      uses: highbyte/sonarscan-dotnet@v2.1.2
      with:
        sonarProjectName: UserService_Hyves-2.0-Backend
        sonarProjectKey: UserService_Hyves-2.0-Backend
        sonarOrganisation: bramhurkmans
        sonarBeginArguments: "UserService.csproj"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
